version: '3.8'
services:
  pdf:
    container_name: pdf-generator
    image: vontainment/gpt-pdf-generator:main  # Use your appropriate image
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "8050:8888"  # Map host port 8050 to container port 8888
    environment:
      # Set this to your actual base URL
      BASE_URL: ""
      # Root path when running behind a reverse proxy
      ROOT_PATH: ""
      # Optional API key to connect to the API
      API_KEY: ""
      # Uvicorn worker count (1 is enough for personal use)
      WORKERS: ""
      # Controls maximum concurrent connections; extras are rejected
      UVICORN_CONCURRENCY: ""
    volumes:
      - pdf-data:/app/downloads  # Ensure downloads directory is persistent

volumes:
  pdf-data:
