  pdf:
    container_name: pdf-generator
    image: vontainment/gpt-pdf-generator:dev  # Use your appropriate image
    restart: always
    ports:
      - "8075:80"  # Map port 80 of the container to port 80 on the host
    environment:
      BASE_URL: https://dify.hugev.xyz
      DIFY: true
      KB_BASE_URL: https://dify.hugev.xyz
      KB_API_KEY: dataset-quUOrwDysLNRlyKE7RhcIPej
    volumes:
      - pdf-data:/app/downloads  # Ensure downloads directory is persistent