name: Build and Push API Image

on:
  push:
    branches:
      - 'main'
      - 'dev'
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code and setup Docker
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # specify the Python version

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Extract metadata and Build & Push Docker image
        uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/vontainment/gpt-pdf-generator
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha,priority=100
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
