name: Build and Push API Image

on:
  push:
    branches:
      - 'main'  
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-20.04  
    steps:
      - name: Check out code
        uses: actions/checkout@v3  

      - name: Setup Docker and Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}  
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: vontainment/gpt-pdf-generator  
          tags: |
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=ref,event=branch
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long
            type=raw,value=${{ github.ref_name }},enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .  
          file: Dockerfile
          push: true  
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            COMMIT_SHA=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline,mode=max
